- hosts: web_nodes
  vars:
    os_packages:
      - python36
      - python36-pip
      - git
      - tree
      - mc
    bucket_name: "204240-legutek"
    python_dependencies:
      - boto3
      - pytest
      - flask 
  tasks:
    - yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ os_packages }}"
      become: yes
    - git:
        repo: https://github.com/Legutek/ani-creator.git
        dest: ~/ani-creator      

    - lineinfile:
        path: ~/.bashrc
        line: "export APP_BUCKET_NAME={{ bucket_name}}"
    - raw: git config --global user.name "Legutek"
    - raw: git config --global user.email "legutekk@gmail.com"
    - pip:
        name: "{{ item }}"
        executable: pip-3.6
      with_items: "{{ python_dependencies }}"
      become: yes
